### ISSUE TITLE
Add Watson Content Analytics Documentation

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.nlp#33]
We have a couple of nice getting started documents here: https://github.com/IBMStreams/streamsx.nlp/tree/master/com.ibm.streamsx.nlp/doc

However, we don't have anything to point users towards Watson Content Analytics Studio. Wouldn't that be our ideal method of analytics development? Would it make sense to point to some useful parts of Watson Content Analytics doc?

**Comment by mgorbat** [comment]
+1 to Alex's request. We only use WCA Studio in client implementations which is a supported product integrated with WCA Server and providing much better experience and tools to the text analytics developer. The output is the same PEAR file, but the process is different. I'd suggest to also reconcile the names of the operators, since currently RutaText implies that it only works with Ruta, although in fact it can work with PEAR files produced by UIMA, UIMA Ruta, WCA Studio, Watson Knowledge Studio.

**Comment by markheger** [comment]
Could you please provide additional documentation or hints to WCA and create a pull-request for this, e.g. in info.xml or README.md?

**Comment by chanskw** [comment]
+1  This is a really good idea.

**Comment by hleuschner** [comment]
Updated dW-Article:
[How to extract text using the IBMStreams Natural Language Processing (NLP) Toolkit RutaText operator?](https://developer.ibm.com/streamsdev/docs/how-to-extract-text-using-the-ibmstreams-extension-text-toolkit-rutatext-operator/)
Old:
How to create a UIMA Ruta PEAR is part of the toolkit documentation.
New:
There are many ways to develop PEAR files. Among them are IBM Watson Content Analytics (ICA) Studio and UIMA Ruta workbench.
One example how to create a UIMA Ruta PEAR is part of the toolkit documentation.
Additional Reference:
IBM Watson Content Analytics (ICA) Studio 
https://www.ibm.com/support/knowledgecenter/en/SS5RWK_3.5.0/com.ibm.discovery.es.in.doc/iiysicasrun.htm
