### ISSUE TITLE
Proposal: Rename project to streamsx.uima to avoid conflict with IBM Text toolkit.

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.nlp#4]
The primary reason for this proposed change is that Streams already includes a Text toolkit in the product.  Referring to this toolkit as the  Extension Text Toolkit is misleading since there is no compatibility and both toolkits present alternative ways of performing text analysis. 
Secondly, since this toolkit provides operators that integrate with Apache UIMA,  it is arguably better to choose a name that is indicative of this.  This would be consistent with the Cassandra, HBase and HDFS toolkits, which integrate with Apache Cassandra, HBase and HDFS respectively.  
Finally, since this toolkit is fairly new, this is a great time to change the name before it gains more popularity and the conflict becomes harder to untangle.

**Comment by joergboe** [comment]
This toolkit covers more aspects than Apache UIMA, thus the name uima toolkit would be misleading as well.

**Comment by markheger** [comment]
I propose to rename the repository to streams.nlp and the namespace of the toolkit to com.ibm.streamsx.nlp to indicate that the toolkit is about Natural Language Processing.

**Comment by hleuschner** [comment]
Here is the comment from Dakshi Agrawal, I received via email:

The new toolkit fundamentally takes a different approach - it is more about natural language processing then text analytics.  I would suggest that we call it streamsx.nlp because our long term goal through this toolkit is Natural Language Processing as opposed to Text Analytics. 

The current streams.text can remain as it is and will become legacy soon.

Current customers who have streamsx.text would need to migrate to streamsx.nlp. Tutorial and demos would need to changed so it is a painful change but I think better for the future.

**Comment by chanskw** [comment]
Let's have a vote for this proposal.  

I vote +1 to rename to streamsx.nlp.

Vote is open for 24 hours (until Nov 15, 2016, 10 am EST)  and if we get enough +1  then we can rename this project.  Thanks!

**Comment by natashadsilva** [comment]
+1 for streamsx.nlp

**Comment by hleuschner** [comment]
+1 for streamsx.nlp

**Comment by chanskw** [comment]
Can I confirm that you have no pending changes for this repository and it is safe to rename today?

**Comment by markheger** [comment]
No pending changes. The latest changes have a tag applied.  It is safe to rename today.

**Comment by chanskw** [comment]
ok Thanks... rename underway.

**Comment by chanskw** [comment]
Repository rename done, github io pages is updated.  Please check if there is any issue.  You will need to update the toolkit, wiki, documentation, etc.

**Comment by markheger** [comment]
The tag v1.2.0 has been applied after renaming to streamsx.nlp.
